import home from '../pages/Home';
export const Routes = [
  {
    path: '/',
    name: 'signup',
    title: 'SIGNUP',
    exact: true,
    component: home,
  },
  // {
  //   path: '/error',
  //   name: 'error',
  //   title: 'ERROR',
  //   exact: true,
  //   component: ErrorScreen,
  // },
  // {
  //   path: '/settings',
  //   name: 'settings',
  //   title: 'SETTINGS',
  //   exact: true,
  //   component: Settings,
  // },
  // {
  //   path: '/setupNetworkMenu',
  //   name: 'setupNetworkMenu',
  //   title: 'SETUP_NETWORK_MENU',
  //   exact: true,
  //   component: SetupNetworkMenu,
  // },

  // {
  //   path: '/setupNetwork',
  //   name: 'setupNetwork',
  //   title: 'SETUP_NETWORK',
  //   exact: true,
  //   component: SetupNetwork,
  // },
  // {
  //   path: '/recovery',
  //   name: 'recovery',
  //   title: 'FORGOT_PASSWORD',
  //   exact: true,
  //   component: Recovery,
  // },
  // {
  //   path: '/setupOrganization',
  //   name: 'setupOrganization',
  //   title: 'SETUP_ORGANIZATION',
  //   exact: true,
  //   component: SetupOrganization,
  // },
  // {
  //   path: '/verifyNode',
  //   name: 'verifyNode',
  //   title: 'VERIFY_NODE',
  //   exact: true,
  //   component: VerifyNode,
  // },
  // {
  //   path: '/auth/login',
  //   name: 'login',
  //   title: 'LOGIN',
  //   exact: true,
  //   component: LoginScreen,
  // },
  // {
  //   path: '/kpis',
  //   name: 'kpis',
  //   title: 'KPIS',
  //   exact: true,
  //   component: Kpis,
  // },
  // {
  //   path: '/verifyEmail',
  //   name: 'verifyEmail',
  //   title: 'VERIFY_EMAIL',
  //   exact: true,
  //   component: VerifyEmail,
  // },

  // {
  //   path: '/installationPictures',
  //   name: 'installationPictures',
  //   title: 'INSTALLATION_PICTURES',
  //   exact: true,
  //   component: InstallationPictures,
  // },
  // {
  //   path: '/',
  //   name: 'login',
  //   title: 'LOGIN',
  //   exact: true,
  //   component: LoginScreen,
  // },
  // {
  //   path: '/dashboard',
  //   name: 'dashboard',
  //   title: 'DASHBOARD',
  //   exact: true,
  //   component: Dashboard,
  // },
  // {
  //   path: '/sites',
  //   name: 'sites',
  //   title: 'SITES',
  //   exact: true,
  //   component: Sites,
  // },
  // {
  //   path: '/sites/details',
  //   name: 'details',
  //   title: 'DETAILS',
  //   exact: true,
  //   component: SiteDetailsPage,
  // },
  // {
  //   path: '/users',
  //   name: 'users',
  //   title: 'USERS',
  //   exact: true,
  //   component: Users,
  // },
  // {
  //   path: '/users/details',
  //   name: 'details',
  //   title: 'USERS',
  //   exact: true,
  //   component: UserDetailsPage,
  // },
  // {
  //   path: '/nodes',
  //   name: 'nodes',
  //   title: 'NODE',
  //   exact: true,
  //   component: Node,
  // },
  // {
  //   path: '/nodes/details',
  //   name: 'nodeDetails',
  //   title: 'DETAILS',
  //   exact: true,
  //   component: NodeDetails,
  // },
];

export default Routes;
